import type { Registry } from 'shadcn/registry';

export const registryUi: Registry['items'] = [
  {
    name: 'form-fields',
    type: 'registry:component',
    title: 'Form Fields Suite',
    description: 'A collection of reusable form field components, hooks, utilities, and types.',
    files: [
      // UI components
      { path: 'components/form-field/ui/BooleanField.tsx', type: 'registry:component' },
      { path: 'components/form-field/ui/ComboboxField.tsx', type: 'registry:component' },
      { path: 'components/form-field/ui/CurrencyField.tsx', type: 'registry:component' },
      { path: 'components/form-field/ui/DateTimeField.tsx', type: 'registry:component' },
      { path: 'components/form-field/ui/FileField.tsx', type: 'registry:component' },
      { path: 'components/form-field/ui/ImageDropZone.tsx', type: 'registry:component' },
      { path: 'components/form-field/ui/NumberField.tsx', type: 'registry:component' },
      { path: 'components/form-field/ui/SelectField.tsx', type: 'registry:component' },
      { path: 'components/form-field/ui/Stepper.tsx', type: 'registry:component' },
      { path: 'components/form-field/ui/SuffixField.tsx', type: 'registry:component' },
      { path: 'components/form-field/ui/SuffixInputField.tsx', type: 'registry:component' },
      { path: 'components/form-field/ui/SuggestField.tsx', type: 'registry:component' },
      { path: 'components/form-field/ui/TextField.tsx', type: 'registry:component' },
      { path: 'components/form-field/ui/ToggleGroup.tsx', type: 'registry:component' },
      { path: 'components/form-field/ui/textAreaField.tsx', type: 'registry:component' },
      { path: 'components/form-field/ui/PasswordField.tsx', type: 'registry:component' },
      { path: 'components/form-field/ui/index.ts', type: 'registry:component' },

      // Hooks
      { path: 'hooks/use-file-upload.ts', type: 'registry:hook' },
      { path: 'hooks/useOptionQuery.ts', type: 'registry:hook' },
      { path: 'hooks/useDebounceState.tsx', type: 'registry:hook' },

      // Lib (form-field)
      { path: 'lib/form-field/form.tsx', type: 'registry:lib' },
      { path: 'lib/form-field/formItem.tsx', type: 'registry:lib' },
      { path: 'lib/form-field/registry.ts', type: 'registry:lib' },
      { path: 'lib/form-field/utils.tsx', type: 'registry:lib' },
      { path: 'lib/form-field/file-storage.ts', type: 'registry:lib' },
      { path: 'lib/form-field/zod-schemas/file.tsx', type: 'registry:lib' },

      // Types
      { path: 'lib/form-field/form-field.ts', type: 'registry:lib' },

      { path: 'components/form-field/ui/button.tsx', type: 'registry:component' },
      { path: 'components/form-field/ui/badge.tsx', type: 'registry:component' },

      { path: 'lib/provider.tsx', type: 'registry:component' },
    ],
    dependencies: [
      'lucide-react',
      '@tanstack/react-query',
      '@lukemorales/query-key-factory',
      'lodash-es',
      '@types/lodash-es',
      'cmdk',
      'date-fns',
      'class-variance-authority',
      'react-aria-components',
      'react-hook-form',
      '@hookform/devtools',
      '@tanstack/react-query-devtools',
      'nuqs',
      'sonner',
    ],
    registryDependencies: [
      'input',
      'checkbox',
      'select',
      'popover',
      'command',
      'textarea',
      'sonner',
      'form',
      'calendar',
      'toggle-group',
    ],
  },
  {
    name: 'data-table',
    type: 'registry:component',
    title: 'Data Table Suite',
    description:
      'A set of reusable data table components, filters, view options, pagination, skeletons, and utilities.',
    files: [
      { path: 'components/data-table/data-table.tsx', type: 'registry:component' },
      { path: 'components/data-table/data-table-column-header.tsx', type: 'registry:component' },
      { path: 'components/data-table/data-table-date-filter.tsx', type: 'registry:component' },
      { path: 'components/data-table/data-table-faceted-filter.tsx', type: 'registry:component' },
      { path: 'components/data-table/data-table-pagination.tsx', type: 'registry:component' },
      { path: 'components/data-table/data-table-skeleton.tsx', type: 'registry:component' },
      { path: 'components/data-table/data-table-slider-filter.tsx', type: 'registry:component' },
      { path: 'components/data-table/data-table-toolbar.tsx', type: 'registry:component' },
      { path: 'components/data-table/data-table-view-options.tsx', type: 'registry:component' },

      { path: 'lib/data-table/utils.tsx', type: 'registry:lib' },
      { path: 'lib/data-table/types/data-table.ts', type: 'registry:lib' },
      { path: 'lib/data-table/config/format.ts', type: 'registry:lib' },
      { path: 'lib/data-table/config/config.ts', type: 'registry:lib' },
      { path: 'lib/data-table/parsers.ts', type: 'registry:lib' },

      { path: 'components/data-table/button.tsx', type: 'registry:component' },
      { path: 'components/data-table/badge.tsx', type: 'registry:component' },
    ],
    dependencies: [
      'lucide-react',
      '@tanstack/react-table',
      '@tanstack/react-query',
      '@lukemorales/query-key-factory',
      'cmdk',
      'date-fns',
      'react-day-picker',
      'clsx',
      'tailwind-merge',
    ],
    registryDependencies: [
      'table',
      'dropdown-menu',
      'select',
      'command',
      'popover',
      'separator',
      'skeleton',
      'label',
      'input',
      'slider',
      'calendar',
    ],
  },
];
